# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[migrations_directory]
dir = "C:\\Tauri-app\\screen_time_tracking_app\\src-tauri\\migrations"
